[package]
name = "SESClient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "*",features = ["full"]}
inquire = {version = "0.6.2"}
colored = "2.0.4"
aws_apis = {git = "https://github.com/Sanjuvi/aws_apis.git"}
reqwest="0.11.20"
dotenv ="0.15.0"